### PR TITLE
5.0.0rc1

### PR DESCRIPTION
**Pull request by dstansby**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by dstansby** [comment]
Hmm, Python 3.11 builds aren't running on this at the moment.

**Comment by Cadair** [comment]
Why no Python 3.11 builds? :thinking:

**Comment by dstansby** [comment]
🤷 I'm guessing because the Python 3.11 migrator didn't affect the `rc` branch. I've just deleted the `rc` branch and started again

**Pull request closed without merging**
