### PR TITLE
Unpin MKL version for Windows.

### PR DESCRIPTION
**Pull request by Cadair**
This will test if the bug with SciPy is fixed.

### CODE REVIEW

**Comment by Cadair** [comment]
This tests if conda-forge/staged-recipes#628 is fixed.

**Comment by jakirkham** [comment]
Looks like you are picking up our `numpy` that is linked to `openblas` actually. Little confused as to what this Linux error is.

cc @pelson

**Comment by jakirkham** [comment]
There we go. AppVeyor didn't seem to pick up on this before. Now it is.

**Comment by jakirkham** [comment]
Restarting CircleCI now that we have SciPy.

**Pull request merged**
