### PR TITLE
4.0rc1

### PR DESCRIPTION
**Pull request by dstansby**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by dstansby** [comment]
I'm going to leave this open, and we can just update the version number and SHA when 4.0 comes out.

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by dstansby** [comment]
@Cadair @wtbarnes @nabobalis This is good to review, and I think should upload a RC to conda-forge

**Comment by Cadair** [comment]
Isn't this missing the build config part mentioned here: https://conda-forge.org/docs/maintainer/knowledge_base.html#creating-a-pre-release-build

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Review by Cadair — APPROVED** [review]

**Comment by dstansby** [comment]
Thanks for catching the missing file, I just forgot to push it

**Review by nabobalis — APPROVED** [review]

**Pull request merged**
